global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # ⚠️ no uses /metrics

  - job_name: 'catalog-service'
    metrics_path: /actuator/prometheus   # ✅ esta es la ruta correcta en Spring Boot
    static_configs:
      - targets: ['host.docker.internal:8001']  # ✅ puerto correcto según tu app
